export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A cat-shaped spaceship hovering over a cheese planet",
  "A jellyfish made of glowing neon lights swimming in space",
  "An owl librarian organizing books in a tree-shaped library",
  "A tea party attended by robots in a Victorian garden",
  "A steampunk elephant walking through a foggy London street",
  "A ghost eating noodles in a Tokyo ramen shop, digital art",
  "A futuristic subway station on the Moon",
  "A castle floating above a lava river in a fantasy realm",
  "A digital art portrait of a lion wearing steampunk goggles",
  "A frog wearing a crown surfing a tsunami wave",
  "A magical forest with bioluminescent mushrooms, fantasy style",
  "A time traveler’s suitcase filled with strange glowing objects",
  "A surreal collage of clocks melting in the desert, inspired by Salvador Dalí",
  "A robot barista serving coffee to aliens on Jupiter",
  "A tiny astronaut sleeping inside a matchbox spaceship",
  "A medieval knight fighting a giant snail in a pixel art style",
  "A goldfish in a robotic tank roaming the desert",
  "A dreamlike city built on top of floating musical instruments",
  "A penguin DJ playing at an icy nightclub, synthwave style",
  "A haunted carousel spinning in an abandoned amusement park",
  "A giraffe with butterfly wings flying through a candy sky",
  "A Viking cat sailing a ship made of yarn",
  "A cybernetic hummingbird drinking from a neon flower",
  "A pizza planet orbited by moons of pepperoni",
  "A surrealist chessboard with moving clouds and shifting tiles",
  "A ballerina robot dancing on a laser-lit stage in deep space",
  "A sea turtle carrying a magical city on its shell",
  "A squirrel knight dueling a duck wizard, storybook art",
  "A group of aliens playing cricket in a Martian desert",
  "A koala in a business suit riding a unicycle across a rainbow",
  "A wizard’s tower filled with floating orbs and scrolls",
  "A noodle dragon flying through a soy sauce storm",
  "A noir-style detective raccoon solving a case in the rain",
  "A futuristic opera house on Saturn’s rings, digital painting",
  "A cactus playing a saxophone under the moonlight",
  "A yeti taking selfies on top of Mount Everest",
  "A neon-lit forest where trees hum music",
  "A hamster operating a mech suit in a battlefield",
  "A watercolor painting of a cat-shaped island",
  "A witch riding a vacuum cleaner through Times Square",
  "A magical doorway inside a vending machine",
  "A realistic photo of a broccoli city with vegetable cars",
  "A chess match between a dragon and a unicorn",
  "A fantasy airship shaped like a pineapple",
  "A dog surfing a lava wave in an erupting volcano",
  "A jelly donut planet with sugar crystal moons",
  "An underwater cafe run by octopuses",
  "A mysterious glowing cave full of ancient computers",
  "A post-apocalyptic world where flowers run the cities",
  "A cyborg deer wandering through a digital rainforest",
];
